site_name: RARE 
site_dir: /home/floui/frederic-loui.github.io
nav:
  - Home: index.md
  - Getting started: index.md
  - Reference guides: 
    - 'Network management': '/guides/mgmt-plane/'
    - 'Routing': '/guides/control-plane/'
    - 'Network service': '/guides/svc-plane/'
    - 'Dataplane': '/guides/data-plane/' 
  - Validated design: 
    - 'SP BGP route reflector': '/rvd/sp-bgp-rr/'
    - 'K8s BGP route reflector': '/rvd/k8s-bgp-rr/'
    - 'MPLS LSR':
      - 'LDP LSR': '/rvd/mpls-lsr/ldp/' 
      - 'ISIS-SR LSR': '/rvd/mpls-lsr/isis-sr/' 
      - 'OSPF-SR LSR': '/rvd/mpls-lsr/ospf-sr/'
    - 'MPLS LER':
      - 'VPNv4/6VPE': '/rvd/mpls-ler/vpnv4-6vpe/' 
      - 'Point to point L2VPN': '/rvd/mpls-ler/p2p-l2vpn/'
      - 'VPLS': '/rvd/mpls-ler/vpls/'
      - 'EVPN': '/rvd/mpls-ler/evpn/' 
  - License: license.md
  - About: about.md
 
theme:
  logo: 'img/rare-icon.png'
  favicon: 'img/favicon.ico'
  name: 'material'
  custom_dir: 'theme' 
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'

extra_css:
  - 'css/extra.css'

extra:
  search:
    language: 'en'
    tokenizer: '[\s\-\.]+'

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  #- pymdownx.betterem:
  #    smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
